image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: javac Minesweeper.java
    command: java -Dsun.java2d.xrender=false Minesweeper
